version: 2.1

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
          - v2-deps-
    - run:
        name: install dependencies
        command: pip install --user tox codecov "coverage<5"
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: upload coverage report
        command: |
           if [[ "$UPLOAD_COVERAGE" != 0 ]]; then
               PATH=$HOME/.local/bin:$PATH
               coverage xml
               ~/.local/bin/codecov --required -X search gcov pycov -f coverage.xml --flags $CIRCLE_JOB
           fi
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          - TOXENV=checkqa
          - UPLOAD_COVERAGE=0
  py36dj22:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj22
  py36dj31:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj31
  py36dj32:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj32
  py37dj22:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-dj22
  py37dj31:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-dj31
  py37dj32:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-dj32
  py38dj22:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj22
  py38dj31:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj31
  py38dj32:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj32
  py39dj22:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV=py39-dj22
  py39dj31:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV=py39-dj31
  py39dj32:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV=py39-dj32
workflows:
  version: 2
  test:
    jobs:
      - lint
      - py36dj22
      - py36dj31
      - py36dj32
      - py37dj22
      - py37dj31
      - py37dj32
      - py38dj22
      - py38dj31
      - py38dj32
      - py39dj22
      - py39dj31
      - py39dj32
