# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_populate_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_filename',
            field=models.CharField(max_length=500),
        ),
    ]
